module NpbPlayersDirectory
  class Giants
    YAML_PATH: String

    @yaml: YAML

    def list_name: (Symbol lang) -> Array[String]

    def load_yaml: -> YAML

    def name_by_uniform_number: (String number) -> String
  end
end
